### ISSUE TITLE
couple questions please

### ISSUE THREAD

**Issue by spirogg** [q3aql/ffmpeg-install#2]
1) I would like to install an older build

https://www.johnvansickle.com/ffmpeg/old-releases/

https://www.johnvansickle.com/ffmpeg/old-releases/ffmpeg-3.3.4-64bit-static.tar.xz

2) I did all the first steps below,

`How to install (ffmpeg-install):
Instructions:

```
Open the terminal.
Clone the repository: git clone https://github.com/q3aql/ffmpeg-install.git
Change directory: cd ffmpeg-install
Copy the script to $PATH (as root): cp -rf ffmpeg-install /usr/bin/
Change the permissions (as root): chmod +x /usr/bin/ffmpeg-install
Note: The script are compatible with all GNU/Linux distributions.`
```
---------------------------------------------------------------------------------

now what would i type in the command line in ssh to get it to install ?

i tried typing in command line :

```
ffmpeg-install --install
and 
ffmpeg-install --install release
```
-------------------------------------------
```
./ffmpeg-install --install
and 
./ffmpeg-install --install release
```

but get keep getting error below?

`Downloading  (wget)
wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
Connection problem!
Exiting...`

can you explain to me in simple words, if i need to edit some code in the ffmpeg-install file
also exact command in the ssh i would need to type to get it to install ffmpeg

Thanks for the help and sorry im a newbie to this stuff

**Comment by badeendjuh** [comment]
You run into this issue because the website this script is based on has changed slightly. The script will need to be adjusted for this. A [pull request](https://github.com/q3aql/ffmpeg-install/pull/1) was already submited. But doing this change manually should be easy.
