### ISSUE TITLE
using FFMPEG to download with the help of URL after 20sec.

### ISSUE THREAD

**Issue by kaushal1208** [q3aql/ffmpeg-install#6]
I want to download youtube video using ffmpeg tool and i took audio-URL and video-URL using " youtube-dl "  but i wish to download particular video after 20 sec of duration  from the start till end.
I don,t  know what are the parameters that i needed to consider and how to do it ?
can anyone provide me related information to it .

**Comment by q3aql** [comment]
I have recently created a tool that allows you to do what you indicate. You can install it with the following commands:

```shell
git clone https://github.com/q3aql/ks-tools
cd ks-tools
sudo make install
```

Then, with the video that you have previously downloaded with `youtube-dl` you execute the following command:

```shell
ks-mix -evat Example.mp4
```

You will see an assistant where you can define from which second you want to start cutting.

```shell
+ Video Tracks:
 Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661)

+ Audio Tracks:
 Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D)

+ audio time:
 Duration: 00:00:06.03

* (Default: 0:0) Type the number of video track: 
* (Default: 0:1) Type the number of audio track: 
* (Default: 0) Type the hour (0-99): 0
* (Default: 1) Type the minute (0-59): 0
* (Default: 0) Type the second (0-59): 20
* (Default: n) Extract audio from 00:00:20 to end? (y/n): y
```
I have also prepared DEB / RPM packages for Debian / Ubuntu or RedHat and even a version for Windows: https://github.com/q3aql/ks-tools
